/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.muonTraSachDAO;
import DAO.sachDAO;
import MODEL.hoTRo;
import POJO.MuonTRaSach;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thuha
 */
public class QL_MuonTra extends javax.swing.JFrame {

    DefaultTableModel modelTB;
    Vector tbTitle = new Vector();
    ArrayList<MuonTRaSach> ds;

    /**
     * Creates new form QL_MuonTra
     */
    public QL_MuonTra() {
        initComponents();
        this.setLocationRelativeTo(null);
        tbTitle.add("Mã mượn trả ");
        tbTitle.add("Mã sinh viên");
        tbTitle.add("Mã sách");
        tbTitle.add("Số lượng SM");
        tbTitle.add("Hình thức mượn");
        tbTitle.add("Quản lý TV");
        tbTitle.add("Ngày mượn");
        tbTitle.add("Ngày trả");

        modelTB = new DefaultTableModel();
        modelTB.setColumnIdentifiers(tbTitle);
        tb_dsQLMuonTra.setModel(modelTB);
        loadDuLieu();
    }

    public void loadDuLieu() {
        ds = muonTraSachDAO.getDSMuonTRa();
        modelTB.setRowCount(0);
        for (MuonTRaSach mt : ds) {
            Vector v = new Vector();
            v.add(mt.getMaMuonTRa());

            v.add(mt.getMaSinhVien());
            v.add(mt.getMaSach());
            v.add(mt.getSoLuongMuon());
            v.add(mt.getHinhThucMuon());
            v.add(mt.getQuanLyThuVien());
            v.add(mt.getNgayMuon());
            v.add(mt.getNgayTRa());
            modelTB.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_quanlythuvien = new javax.swing.JTextField();
        txt_masv = new javax.swing.JTextField();
        txt_masach = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ngaymuon = new javax.swing.JTextField();
        txt_ngaytra = new javax.swing.JTextField();
        txt_hinhthucmuon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_mamuontra = new javax.swing.JTextField();
        txt_sluongmuon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dsQLMuonTra = new javax.swing.JTable();
        btn_hinhnen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_reset = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_timkiemma = new javax.swing.JTextField();
        btn_tim = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Mượn,Trả Sách");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Library-icon (2).png"))); // NOI18N
        jLabel1.setText("Thực Hiện Mượn, Trả Sách");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/library-icon (1).png"))); // NOI18N
        jLabel2.setText("Quản Lý Mượn, Trả Sách");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 2));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Mã SV:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Mã Sách:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Hình Thức Mượn:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Quản Lý TV:");

        txt_quanlythuvien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_masv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_masach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Số Lượng Mượn:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Ngày Mượn:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Ngày Trả:");

        txt_ngaymuon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_ngaytra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_hinhthucmuon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Mã MT:");

        txt_sluongmuon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_quanlythuvien, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_masach, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ngaytra, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hinhthucmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_mamuontra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(txt_masv, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txt_sluongmuon, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_mamuontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_masach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_sluongmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_hinhthucmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_quanlythuvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_ngaytra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_hinhthucmuon, txt_masach, txt_masv, txt_ngaymuon, txt_ngaytra, txt_quanlythuvien});

        tb_dsQLMuonTra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tb_dsQLMuonTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_dsQLMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_dsQLMuonTraMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dsQLMuonTra);

        btn_hinhnen.setBackground(new java.awt.Color(255, 204, 102));
        btn_hinhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documents-icon.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Library-icon (2).png"))); // NOI18N
        jLabel3.setText("Xử Lý");

        btn_print.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btn_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/write-paper-ink-icon.png"))); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reset-icon (3).png"))); // NOI18N
        btn_reset.setText("Mượn Mới");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Knob-Fast-Rewind-icon.png"))); // NOI18N
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        btn_them.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Knob-Add-icon.png"))); // NOI18N
        btn_them.setText("Cho Mượn");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Knob-Cancel-icon.png"))); // NOI18N
        btn_xoa.setText("Trả Sách");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_them, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_reset, btn_them, btn_thoat, btn_xoa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thoat)
                    .addComponent(btn_xoa))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_reset, btn_them, btn_thoat, btn_xoa});

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Log-Off-icon (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 204));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Knob-Fast-Forward-icon.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        txt_timkiemma.setBackground(new java.awt.Color(255, 204, 102));
        txt_timkiemma.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_timkiemma.setText("Search.....");
        txt_timkiemma.setToolTipText("");
        txt_timkiemma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_timkiemmaMouseClicked(evt);
            }
        });
        txt_timkiemma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemmaActionPerformed(evt);
            }
        });
        txt_timkiemma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timkiemmaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timkiemmaKeyReleased(evt);
            }
        });

        btn_tim.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom-icon.png"))); // NOI18N
        btn_tim.setText("Tìm Sinh Viên");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("CHI TIẾT THÔNG TIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Mã MT:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_timkiemma, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_timkiemma, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_tim)))
                .addGap(27, 27, 27))
        );

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 204));
        jButton2.setText("Hiển Thị Thông Tin Đầy Đủ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(131, 131, 131)
                                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_hinhnen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton4)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hinhnen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btn_print))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login them = new Login();
        them.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        QL_ThuVien them = new QL_ThuVien();
        them.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        int ext = JOptionPane.showConfirmDialog(this, "Do you want exit", "Thong bao", JOptionPane.YES_NO_OPTION);
        if (ext == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_btn_thoatActionPerformed
    public void reset() {
        txt_mamuontra.setText("");

        txt_hinhthucmuon.setText("");
        txt_masach.setText("");
        txt_masv.setText("");
        txt_ngaymuon.setText("");
        txt_ngaytra.setText("");
        txt_quanlythuvien.setText("");
        txt_mamuontra.requestFocus();
        txt_sluongmuon.setText("");
    }
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tb_dsQLMuonTraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dsQLMuonTraMouseReleased
        int row = tb_dsQLMuonTra.getSelectedRow();
        if (row >= 0) {
            txt_mamuontra.setText((String) (tb_dsQLMuonTra.getValueAt(row, 0)));

            txt_masv.setText((String) (tb_dsQLMuonTra.getValueAt(row, 1)));
            txt_masach.setText((String) (tb_dsQLMuonTra.getValueAt(row, 2)));
            txt_sluongmuon.setText((tb_dsQLMuonTra.getValueAt(row, 3)).toString());
            txt_hinhthucmuon.setText((String) (tb_dsQLMuonTra.getValueAt(row, 4)));
            txt_quanlythuvien.setText((String) (tb_dsQLMuonTra.getValueAt(row, 5)));
            txt_ngaymuon.setText((String) (tb_dsQLMuonTra.getValueAt(row, 6).toString()));
            txt_ngaytra.setText((String) (tb_dsQLMuonTra.getValueAt(row, 7).toString()));

        }
    }//GEN-LAST:event_tb_dsQLMuonTraMouseReleased
    boolean ktraMaMT(String maMT) {
        String ktra = "MT\\d+";
        if (maMT.matches(ktra)) {
            return true;
        }
        return false;
    }

    boolean ktraMaSV(String maSV) {
        String ktra = "SV\\d+";
        if (maSV.matches(ktra)) {
            return true;
        }
        return false;
    }

    boolean ktraMaS(String maS) {
        String ktra = "MS\\d+";
        if (maS.matches(ktra)) {
            return true;
        }
        return false;
    }
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed

        if (hoTRo.checkRong(txt_mamuontra) || hoTRo.checkRong(txt_masv) || hoTRo.checkRong(txt_masach) || hoTRo.checkRong(txt_hinhthucmuon) || hoTRo.checkRong(txt_ngaymuon) || hoTRo.checkRong(txt_ngaytra) || hoTRo.checkRong(txt_quanlythuvien)) {
            return;
        }

        if (!ktraMaMT(txt_mamuontra.getText())) {
            JOptionPane.showMessageDialog(this, "Ma MT co dang MTxx voi x la chu so", "Thong bao", 1);

            txt_mamuontra.setText("");
            txt_mamuontra.requestFocus();

            return;
        }

        if (!ktraMaSV(txt_masv.getText())) {
            JOptionPane.showMessageDialog(this, "Ma SV co dang SVxx voi x la chu so", "Thong bao", 1);

            txt_masv.setText("");
            txt_masv.requestFocus();

            return;
        }
        if (!ktraMaS(txt_masach.getText())) {
            JOptionPane.showMessageDialog(this, "Ma Sach co dang MSxx voi x la chu so", "Thong bao", 1);

            txt_masach.setText("");
            txt_masach.requestFocus();

            return;
        }
        if (!(txt_hinhthucmuon.getText().trim().equals("Mượn tại chỗ") || txt_hinhthucmuon.getText().trim().equals("Mượn về nhà"))) {
            JOptionPane.showMessageDialog(this, " Hinh thuc muon Mượn tại chỗ hoạc Mượn về nhà)", "Thong bao", 1);
            txt_hinhthucmuon.setText("");
            txt_hinhthucmuon.requestFocus();
            return;
        }
        if (Integer.parseInt(txt_sluongmuon.getText().toString()) > 3) {
            JOptionPane.showMessageDialog(null, "Số lượng mượn không được lớn hơn 3 quyển", "thong bao", 1);
            txt_sluongmuon.setText("");
            txt_sluongmuon.requestFocus();
            return;
        }
        Date ngayMuon, ngayTra;
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            ngayMuon = df.parse(txt_ngaymuon.getText().trim());
            ngayTra = df.parse(txt_ngaytra.getText().trim());
        } catch (Exception e) {
            System.out.println("");
            return;
        }
        System.out.println(ngayMuon + " " + ngayTra);
        if (ngayMuon.compareTo(ngayTra) >= 0) {
            JOptionPane.showMessageDialog(null, "Ngay muon luon nho hon hoac bang ngay tra", "thong bao", 1);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Ban co muon cho muon sach   nay khong", "Thong bao", 1) == JOptionPane.YES_NO_OPTION) {
            int i = muonTraSachDAO.them(txt_mamuontra.getText().trim(), txt_masv.getText().trim(), txt_masach.getText().trim(),   Integer.parseInt(txt_sluongmuon.getText()), txt_hinhthucmuon.getText().trim(), txt_quanlythuvien.getText().trim(),
                  txt_ngaymuon.getText().trim(), txt_ngaytra.getText().trim());

            if (i != -1) {
                JOptionPane.showMessageDialog(this, "Ban da them thanh cong", "Thong bao", 1);
                reset();
                loadDuLieu();

            }
        }

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed

        if (hoTRo.checkRong(txt_mamuontra) || hoTRo.checkRong(txt_masv) || hoTRo.checkRong(txt_masach) || hoTRo.checkRong(txt_hinhthucmuon) || hoTRo.checkRong(txt_ngaymuon) || hoTRo.checkRong(txt_ngaytra) || hoTRo.checkRong(txt_quanlythuvien)) {
            return;
        }
        int tb = tb_dsQLMuonTra.getSelectedRow();
        if (tb >= 0) {
            if (JOptionPane.showConfirmDialog(null, "Ban co muon xoa  nay", "Thong bao", 1) == JOptionPane.YES_OPTION) {
                int i = muonTraSachDAO.xoaMTra(tb_dsQLMuonTra.getValueAt(tb, 0).toString());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Ban da xoa thanh cong", "Thong bao", 1);
                    loadDuLieu();
                    reset();
                }
            }
        }


    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        String filef = "src//FILE//DSMuonTra_Sach.txt";
        File file = new File(filef);

        try {
            if (JOptionPane.showConfirmDialog(this, "Ban co muon luu vao file txt khong", "Thong bao", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                FileWriter fw = new FileWriter(file);
                BufferedWriter bw = new BufferedWriter(fw);
                JOptionPane.showMessageDialog(this, "Ban da luu file thanh cong", "Thong bao", 2);

                for (int i = 0; i < tb_dsQLMuonTra.getRowCount(); i++) {
                    for (int j = 0; j < tb_dsQLMuonTra.getColumnCount(); j++) {

                        bw.write(tb_dsQLMuonTra.getValueAt(i, j).toString() + "      ");

                    }

                    bw.newLine();
                }

                bw.close();
                fw.close();
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_printActionPerformed

    private void txt_timkiemmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timkiemmaMouseClicked

        txt_timkiemma.setText("");
    }//GEN-LAST:event_txt_timkiemmaMouseClicked

    private void txt_timkiemmaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemmaKeyReleased
        modelTB = (DefaultTableModel) tb_dsQLMuonTra.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelTB);
        tb_dsQLMuonTra.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_timkiemma.getText().trim()));


    }//GEN-LAST:event_txt_timkiemmaKeyReleased

    private void txt_timkiemmaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemmaKeyPressed

        modelTB = (DefaultTableModel) tb_dsQLMuonTra.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelTB);
        tb_dsQLMuonTra.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_timkiemma.getText().trim()));


    }//GEN-LAST:event_txt_timkiemmaKeyPressed

    private void txt_timkiemmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemmaActionPerformed
    boolean ktraRong(JTextField txt) {
        if (txt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, txt.getName() + " không được rỗng", "Thông báo", 1);
            txt.requestFocus();
            return true;
        }
        return false;
    }
    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        if (ktraRong(txt_timkiemma)) {
            return;
        }
        modelTB.setRowCount(0);
        ArrayList<MuonTRaSach> dshd = muonTraSachDAO.timB(txt_timkiemma.getText().trim());
        for (MuonTRaSach hd : dshd) {
            Vector r = new Vector();
            r.add(hd.getMaMuonTRa());
            r.add(hd.getMaSinhVien());
            r.add(hd.getMaSach());

            r.add(hd.getSoLuongMuon());
            r.add(hd.getHinhThucMuon());
            r.add(hd.getQuanLyThuVien());
            r.add(hd.getNgayMuon());
            r.add(hd.getNgayTRa());

            modelTB.addRow(r);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_btn_timActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (ktraRong(txt_timkiemma)) {
            return;
        }
        boolean check = false;
        for (MuonTRaSach b : muonTraSachDAO.getDSMuonTRa()) {
            if (b.getMaMuonTRa().toLowerCase().trim().equals(txt_timkiemma.getText().trim().toLowerCase())) {
                check = true;
                break;
            }
        }
        if (!check) {
            JOptionPane.showMessageDialog(null, "Không có mã MT nay", "Thông báo", 1);
            return;
        } else {
            new NewJDialog(this, rootPaneCheckingEnabled, txt_timkiemma.getText()).setVisible(true);
//            NewJDialog them = new  NewJDialog();
//            them.setVisible(true);
        }
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loadDuLieu();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QL_MuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QL_MuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QL_MuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QL_MuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QL_MuonTra().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hinhnen;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_dsQLMuonTra;
    private javax.swing.JTextField txt_hinhthucmuon;
    private javax.swing.JTextField txt_mamuontra;
    private javax.swing.JTextField txt_masach;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_ngaymuon;
    private javax.swing.JTextField txt_ngaytra;
    private javax.swing.JTextField txt_quanlythuvien;
    private javax.swing.JTextField txt_sluongmuon;
    private javax.swing.JTextField txt_timkiemma;
    // End of variables declaration//GEN-END:variables
}
