/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.sachDAO;
import MODEL.hoTRo;
import POJO.Sach;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author thuha
 */
public class QL_Sach extends javax.swing.JFrame {

    DefaultTableModel modelTB;
    Vector tbTitle = new Vector();
    ArrayList<Sach> ds;

    /**
     * Creates new form QL_Sach
     */
    public QL_Sach() {
        initComponents();
        this.setLocationRelativeTo(null);
        tbTitle.add("Mã Sách ");
        tbTitle.add("Tên Sách");
        tbTitle.add("Tác Giả");
        tbTitle.add("Năm XB");
        tbTitle.add("Loại");
        tbTitle.add("Số Trang ");
        tbTitle.add("Giá");
        tbTitle.add("Tình Trạng");

        modelTB = new DefaultTableModel();
        modelTB.setColumnIdentifiers(tbTitle);
        tb_DSSach.setModel(modelTB);
        loadDuLieu();

    }

    public void loadDuLieu() {
        ds = sachDAO.getDSSach();
        modelTB.setRowCount(0);
        for (Sach mt : ds) {
            Vector v = new Vector();
            v.add(mt.getMaSach());

            v.add(mt.getTenSach());
            v.add(mt.getTacGia());
            v.add(mt.getNamXuatBan());
            v.add(mt.getLoai());
            v.add(mt.getSoTrang());
            v.add(mt.getGia());
            v.add(mt.getTinhTrang());

            modelTB.addRow(v);
        }
        lb_soluong.setText(""+ds.size());
    }

    boolean ktraMaS(String maSach) {
        String ktra = "MS\\d+";
        if (maSach.matches(ktra)) {
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Gia = new javax.swing.JTextField();
        txt_loaiSach = new javax.swing.JTextField();
        txt_namXB = new javax.swing.JTextField();
        txt_masach = new javax.swing.JTextField();
        txt_tenSach = new javax.swing.JTextField();
        txt_tacgia = new javax.swing.JTextField();
        btn_luu = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        txt_timKiem = new javax.swing.JTextField();
        btn_in = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_DSSach = new javax.swing.JTable();
        txt_soTrang = new javax.swing.JTextField();
        txt_tinhtrang = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        lb_sum = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lb_soluong = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ SÁCH");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("QUẢN LÝ SÁCH");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mã Sách:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Tên Sách:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tác Giả:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Số Trang:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Năm xuất bản:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Giá:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Loại Sách:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Tình Trạng:");

        txt_Gia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_loaiSach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_namXB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_masach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_tenSach.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_tacgia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btn_luu.setBackground(new java.awt.Color(102, 0, 0));
        btn_luu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_luu.setForeground(new java.awt.Color(255, 255, 204));
        btn_luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Knob-Add-icon.png"))); // NOI18N
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(255, 255, 204));
        btn_xoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(102, 0, 0));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Knob-Cancel-icon.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(0, 51, 51));
        btn_sua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(204, 255, 204));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pen-icon (3).png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_them.setBackground(new java.awt.Color(0, 102, 102));
        btn_them.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_them.setForeground(new java.awt.Color(204, 255, 204));
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_thoat.setBackground(new java.awt.Color(0, 0, 102));
        btn_thoat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_thoat.setForeground(new java.awt.Color(204, 204, 255));
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        txt_timKiem.setBackground(new java.awt.Color(0, 204, 204));
        txt_timKiem.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_timKiem.setText("Search..................");
        txt_timKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_timKiemMouseClicked(evt);
            }
        });
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });
        txt_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timKiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timKiemKeyReleased(evt);
            }
        });

        btn_in.setBackground(new java.awt.Color(51, 0, 51));
        btn_in.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_in.setForeground(new java.awt.Color(204, 204, 0));
        btn_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print-icon.png"))); // NOI18N
        btn_in.setText("Print");
        btn_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inActionPerformed(evt);
            }
        });

        btn_timkiem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document-search-icon.png"))); // NOI18N
        btn_timkiem.setText("Tìm kiếm sách");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)), "DANH SACH SACH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N

        tb_DSSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_DSSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_DSSachMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tb_DSSach);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Log-Off-icon (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 204, 204));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Knob-Fast-Forward-icon.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btn_huy.setBackground(new java.awt.Color(0, 0, 102));
        btn_huy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_huy.setForeground(new java.awt.Color(204, 204, 255));
        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        lb_sum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 204));
        jButton2.setText("***************************************************************************************************");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Số lượng sách:");

        lb_soluong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_tenSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_tacgia, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_soTrang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_masach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(26, 26, 26)
                                                .addComponent(txt_loaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(66, 66, 66)
                                                .addComponent(txt_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_namXB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(btn_them)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lb_soluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lb_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_in, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(38, 38, 38)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_huy, btn_them, btn_thoat});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_masach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_namXB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_loaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_xoa)
                        .addGap(45, 45, 45)
                        .addComponent(btn_sua)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_thoat)
                    .addComponent(btn_huy))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_sum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lb_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)))
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_masach, txt_soTrang, txt_tacgia, txt_tenSach});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_Gia, txt_loaiSach, txt_namXB, txt_tinhtrang});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_huy, btn_luu, btn_sua, btn_them, btn_thoat, btn_xoa});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        int t = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát chương trình hay không? ", "Thong bao", JOptionPane.YES_NO_CANCEL_OPTION);
        if (t == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void tb_DSSachMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DSSachMouseReleased
        int tb = tb_DSSach.getSelectedRow();
        if (tb >= 0) {
            txt_masach.setText((String) (tb_DSSach.getValueAt(tb, 0)));
            txt_tenSach.setText((String) (tb_DSSach.getValueAt(tb, 1)));
            txt_tacgia.setText((String) (tb_DSSach.getValueAt(tb, 2)));
            txt_namXB.setText((String) (tb_DSSach.getValueAt(tb, 3).toString()));
            txt_loaiSach.setText((String) (tb_DSSach.getValueAt(tb, 4)));
            txt_Gia.setText((String) (tb_DSSach.getValueAt(tb, 5).toString()));

            txt_soTrang.setText((String) (tb_DSSach.getValueAt(tb, 6).toString()));
            txt_tinhtrang.setText((String) (tb_DSSach.getValueAt(tb, 7)));
            btn_sua.setEnabled(true);
            btn_huy.setEnabled(false);
            btn_luu.setEnabled(false);
            btn_xoa.setEnabled(true);
            btn_them.setEnabled(true);
        }

    }//GEN-LAST:event_tb_DSSachMouseReleased
    public void reSet() {
        txt_Gia.setText("");
        txt_loaiSach.setText("");
        txt_masach.setText("");
        txt_namXB.setText("");
        txt_tacgia.setText("");
        txt_tenSach.setText("");
        txt_tinhtrang.setText("");
        txt_soTrang.setText("");
    }
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        reSet();

        btn_huy.setEnabled(true);
        btn_luu.setEnabled(true);

        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed

        if (hoTRo.checkRong(txt_Gia) || hoTRo.checkRong(txt_loaiSach) || hoTRo.checkRong(txt_masach)
                || hoTRo.checkRong(txt_namXB) || hoTRo.checkRong(txt_soTrang) || hoTRo.checkRong(txt_tacgia)
                || hoTRo.checkRong(txt_tenSach) || hoTRo.checkRong(txt_tinhtrang)) {
            return;
        }
        if (!ktraMaS(txt_masach.getText())) {
            JOptionPane.showMessageDialog(this, "Ma sach co dang MSxx voi x la chu so", "Thong bao", 1);

            txt_masach.setText("");
            txt_masach.requestFocus();

            return;
        }
        if (!hoTRo.kt_soTrang(Integer.parseInt(txt_soTrang.getText()))) {
            JOptionPane.showMessageDialog(this, "Số trang sách phải lớn hơn 0", "Thong bao", 1);
            txt_soTrang.setText("");
            txt_soTrang.requestFocus();
            return;

        }
        if (!hoTRo.ktraNamXB(Integer.parseInt(txt_namXB.getText()))) {
            JOptionPane.showMessageDialog(this, "Nam XB tu 1975 den 2021", "Thong bao", 1);
            txt_namXB.setText("");
            txt_namXB.requestFocus();
            return;
        }
        if (!(txt_tinhtrang.getText().trim().equals("Còn") || txt_tinhtrang.getText().trim().equals("Hết"))) {
            JOptionPane.showMessageDialog(this, "Tình trạng Còn hoặc Hết", "Thong bao", 1);
            txt_tinhtrang.setText("");
            txt_tinhtrang.requestFocus();
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Ban co muon them khong", "Thong bao", 1) == JOptionPane.YES_NO_OPTION) {
            int i = sachDAO.themSach(txt_masach.getText().trim(), txt_tenSach.getText().trim(), txt_tacgia.getText().trim(),
                    Integer.parseInt(txt_namXB.getText()), txt_loaiSach.getText().trim(), Integer.parseInt(txt_soTrang.getText()),
                    Integer.parseInt(txt_Gia.getText()), txt_tinhtrang.getText().trim());

            if (i != -1) {
                JOptionPane.showMessageDialog(this, "Ban da them thanh cong", "Thong bao", 1);

                loadDuLieu();
                reSet();
            }
        }


    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        btn_them.setEnabled(false);
        btn_sua.setEnabled(false);

        btn_huy.setEnabled(true);
        btn_luu.setEnabled(true);
        if (hoTRo.checkRong(txt_Gia) || hoTRo.checkRong(txt_loaiSach) || hoTRo.checkRong(txt_masach)
                || hoTRo.checkRong(txt_namXB) || hoTRo.checkRong(txt_soTrang) || hoTRo.checkRong(txt_tacgia)
                || hoTRo.checkRong(txt_tenSach) || hoTRo.checkRong(txt_tinhtrang)) {
            return;
        }
        int tb = tb_DSSach.getSelectedRow();
        if (tb >= 0) {
            if (JOptionPane.showConfirmDialog(null, "Ban co muon xoa sach nay khong", "Thong bao", 1) == JOptionPane.YES_OPTION) {
                int i = sachDAO.xoaSach(tb_DSSach.getValueAt(tb, 0).toString());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Ban da xoa thanh cong", "Thong bao", 1);
                    loadDuLieu();

                }
            }
        }


    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        btn_xoa.setEnabled(false);
        btn_them.setEnabled(false);

        btn_luu.setEnabled(true);
        btn_huy.setEnabled(true);

        int row = tb_DSSach.getSelectedRow();
        if (row >= 0) {

            if (hoTRo.checkRong(txt_Gia) || hoTRo.checkRong(txt_loaiSach) || hoTRo.checkRong(txt_masach)
                    || hoTRo.checkRong(txt_namXB) || hoTRo.checkRong(txt_soTrang) || hoTRo.checkRong(txt_tacgia)
                    || hoTRo.checkRong(txt_tenSach) || hoTRo.checkRong(txt_tinhtrang)) {
                return;
            }
            if (!ktraMaS(txt_masach.getText())) {
                JOptionPane.showMessageDialog(this, "Ma sach co dang MSxx voi x la chu so", "Thong bao", 1);

                txt_masach.setText("");
                txt_masach.requestFocus();

                return;
            }
            if (!hoTRo.kt_soTrang(Integer.parseInt(txt_soTrang.getText()))) {
                JOptionPane.showMessageDialog(this, "Số trang sách phải lớn hơn 0", "Thong bao", 1);
                txt_soTrang.setText("");
                txt_soTrang.requestFocus();
                return;

            }
            if (!hoTRo.ktraNamXB(Integer.parseInt(txt_namXB.getText()))) {
                JOptionPane.showMessageDialog(this, "Nam XB tu 1975 den 2021", "Thong bao", 1);
                txt_namXB.setText("");
                txt_namXB.requestFocus();
                return;
            }
            if (!(txt_tinhtrang.getText().trim().equals("Còn") || txt_tinhtrang.getText().trim().equals("Hết"))) {
                JOptionPane.showMessageDialog(this, "Tình trạng Còn hoặc Hết", "Thong bao", 1);
                txt_tinhtrang.setText("");
                txt_tinhtrang.requestFocus();
                return;
            }
            if (JOptionPane.showConfirmDialog(null, "Bạn muốn sửa sách này khong", "Thông báo", JOptionPane.YES_NO_OPTION, 1) == JOptionPane.YES_OPTION) {
                int i = sachDAO.updateSach(txt_masach.getText(), txt_tenSach.getText(), txt_tacgia.getText(), Integer.parseInt(txt_namXB.getText()),
                        txt_loaiSach.getText(), Integer.parseInt(txt_soTrang.getText()), Integer.parseInt(txt_Gia.getText()), txt_tinhtrang.getText());
                if (i != -1) {
                    JOptionPane.showMessageDialog(null, "Đã sửa thanh cong", "Thông báo", 1);

                    loadDuLieu();
                }
            }
        }


    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        Tim_Sach them = new Tim_Sach();
        them.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inActionPerformed
        String filef = "src//FILE//DS_Sach.txt";
        File file = new File(filef);

        try {
            if (JOptionPane.showConfirmDialog(this, "Ban co muon luu vao file txt khong", "Thong bao", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                FileWriter fw = new FileWriter(file);
                BufferedWriter bw = new BufferedWriter(fw);
                JOptionPane.showMessageDialog(this, "Ban da luu file thanh cong", "Thong bao", 2);

                for (int i = 0; i < tb_DSSach.getRowCount(); i++) {
                    for (int j = 0; j < tb_DSSach.getColumnCount(); j++) {

                        bw.write(tb_DSSach.getValueAt(i, j).toString() + "      ");

                    }

                    bw.newLine();
                }

                bw.close();
                fw.close();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_inActionPerformed

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed


    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login them = new Login();
        them.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        QL_ThuVien them = new QL_ThuVien();
        them.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txt_timKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timKiemMouseClicked
        txt_timKiem.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemMouseClicked

    private void txt_timKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKiemKeyReleased
        modelTB = (DefaultTableModel) tb_DSSach.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelTB);
        tb_DSSach.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_timKiem.getText().trim()));

    }//GEN-LAST:event_txt_timKiemKeyReleased

    private void txt_timKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKiemKeyPressed
//        modelTB = (DefaultTableModel) tb_DSSach.getModel();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(modelTB);
//        tb_DSSach.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(txt_timKiem.getText().trim()));

    }//GEN-LAST:event_txt_timKiemKeyPressed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        reSet();

        btn_them.setEnabled(false);

        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_huyActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QL_Sach.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QL_Sach.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QL_Sach.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QL_Sach.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QL_Sach().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_in;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_soluong;
    private javax.swing.JLabel lb_sum;
    private javax.swing.JTable tb_DSSach;
    private javax.swing.JTextField txt_Gia;
    private javax.swing.JTextField txt_loaiSach;
    private javax.swing.JTextField txt_masach;
    private javax.swing.JTextField txt_namXB;
    private javax.swing.JTextField txt_soTrang;
    private javax.swing.JTextField txt_tacgia;
    private javax.swing.JTextField txt_tenSach;
    private javax.swing.JTextField txt_timKiem;
    private javax.swing.JTextField txt_tinhtrang;
    // End of variables declaration//GEN-END:variables
}
